# Change these first
owner: PbtServers # Your GitHub organization or username, where this repository lives
repo: PbtServers-Estado # The name of this repository

sites:
  - name: PbtServers (GLOBAL)
    url: https://pbtservers.com
  - name: PbtTickets
    url: https://tickets.pbtservers.com
  - name: PbtHosting (Panel)
    url: https://pbth.pbtservers.com
  - name: PbtModsURL
    url: https://mods.pbtservers.com
  #- name: PbtServers (Minecraft)
  #  check: "udp-ping"
  #  url: mc.pbtservers.com
  #  port: 25565
  #- name: PbtServers (GLOBAL)
    #url: https://pbtservers.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.pbtservers.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/68289322?v=4
  name: PbtServers-Estado
  introTitle: PbtServers-Estado
  introMessage: Página de Estado Actual de PbtServers
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/PbtServers/PbtServers-Estado

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
